### ISSUE TITLE
Add "3pfree" as a 'legal' prefix

### ISSUE THREAD

**Issue by CharlieMouton** [gpauloski/3pseatBot#136]
### Describe the Request

I often share games, etc that are free to claim to the group and it would be fun to have a prefix that uplifts and simplifies those posts, a la 3pfeet, etc.

**Comment by gpauloski** [comment]
This is a runtime configuration option available via the `/rules configure` command. I went ahead and updated the configuration within the Discord Guilds that 3pseatBot is enabled within, but otherwise the allowed prefixes are not enumerated anywhere in the code base.
